import type { NextPage } from 'next';
import Head from 'next/head';
import styles from "../../styles/Home.module.css";
import {useRouter} from "next/router";
import {useState} from "react";

const Decks: NextPage = () => {

    const router = useRouter();
    const [decks, setDecks] = useState<[]>([]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Decks | Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Decks
                </h1>

                <ul>
                    {decks && decks.length > 0 ? (
                        decks.map((element, index) => {
                            return (<li key={index}>{element}</li>);
                        })) : (<p>no decks found</p>)
                    }
                </ul>

            </main>
        </div>
    );
}

export default Decks;
