import {NextPage} from "next";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import Link from "next/link";

const Dev: NextPage = () => {

    return (
        <div className={styles.container}>
            <Head>
                <title>Dev | Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Dev
                </h1>

                <ul>
                    <li>
                        <Link href={"/dev/decks"}>Decks</Link>
                    </li>
                    <li>
                        <Link href={"/dev/players"}>Players</Link>
                    </li>
                    <li>
                        <Link href={"/dev/playground"}>Playground</Link>
                    </li>
                </ul>
            </main>
        </div>
    );

}

export default Dev;