import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import CardHolder from "../../components/CardHolder";

const Playground: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Playground | Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Playground
                </h1>

                <div>
                    <CardHolder/>
                </div>
            </main>
        </div>
    )
}

export default Playground;
