import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Infinite Cards
                </h1>

                <p className={styles.description}>
                    An infinite amount of cards for an infinite amount of games!
                </p>

                <div className={styles.grid}>
                    <Link href={"/deck"}>
                        <div className={styles.card}>
                            <h2>Deck</h2>
                            <p>Create a deck</p>
                        </div>
                    </Link>

                    <Link href={"/player"}>
                        <div className={styles.card}>
                            <h2>Player</h2>
                            <p>Join a deck</p>
                        </div>
                    </Link>
                </div>
            </main>

            <footer className={styles.footer}>
                <h3>
                    <Link href={"/dev"}>Dev</Link>
                </h3>
            </footer>
        </div>
    );
}

export default Home;
