import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Infinite Cards
                </h1>

                <p className={styles.description}>
                    An infinite amount of cards for an infinite amount of games!
                </p>

                <div className={styles.grid}>
                    <a href="/deck" className={styles.card}>
                        <h2>Deck;</h2>
                        <p>Create the deck</p>
                    </a>

                    <a href="/player" className={styles.card}>
                        <h2>Player</h2>
                        <p>Join a deck</p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
