import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import QRCode from "react-qr-code"
import {useRouter} from "next/router";

const DeckInfo: NextPage = () => {

    const router = useRouter();
    const {id} = router.query;

    return (
        <div className={styles.container}>
            <Head>
                <title>Deck | Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Deck
                </h1>
                <p>{id}</p>
                <br/>
                <p>Scan the QR Code to join this deck!</p>
                <QRCode value={`https://infinitecards.tomheaton.dev/api/join?id=${id}`}/>
            </main>
        </div>
    );
}

export default DeckInfo;
