import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import {useRouter} from "next/router";

const Deck: NextPage = () => {
    const router = useRouter();

    const handleCreateDeck = () => {
        router.push("deck/create");
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Deck | Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Deck
                </h1>

                <p className={styles.description}>
                    Create a deck.
                </p>

                <button onClick={handleCreateDeck}>Create</button>
            </main>
        </div>
    )
}

export default Deck;
