import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {useState} from "react";

/*export const getServerSideProps: GetServerSideProps = async (context) => {

    try {

        return {
            props: {

            }
        }
    } catch (error) {
        console.log("error", error)
        throw error
    }
}*/

const CreateDeck: NextPage = () => {

    const [id, setId] = useState<string>("");

    const handleSubmit = async (e: any) => {
        e.preventDefault();
        const result = await fetch("http://localhost:3000/api/sessions/join", {
            method: "POST",
            body: JSON.stringify({id: id}),
            headers: {"Content-Type": "application/json"}
        })

        console.log("result", result.json())
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Join | Deck | Infinite Cards</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Join a Deck
                </h1>
                <p>Enter an ID to join a deck.</p>
                <input style={{width: "300px"}} onChange={(e) => {setId(e.target.value)}} type={"string"} placeholder={"a685a9cc-e690-4eec-9bfb-2a9ff8e3a405"}/>
                {id.length > 0 && (<button onClick={handleSubmit}>Join</button>)}
            </main>
        </div>
    );
}

export default CreateDeck;
